apiVersion: v1
kind: Service
metadata:
  name: nccl-svc
  namespace: default
spec:
  clusterIP: None # This makes the service "headless"
  selector:
    # This selector must match the pods created by your Job.
    # Kubernetes automatically adds this label to pods managed by a Job.
    job-name: nccl-dws-job
